### ISSUE TITLE
Standardize error logging

### ISSUE THREAD

**Issue by Hyodar** [NethermindEth/near-sffl#179]
Sometimes we are logging errors using a separate tag, like:
```go
logger.Error("Something happened!", "err", err)
```
And sometimes we are using a format string, e.g.:
```go
logger.Errorf("Something happened: %w", err)
```

I'd say the tag one seems better (my vote), and that's what we've been trying to follow, but either way we need to chose one standard and refactor the usages. Should be quick, just some manual work.

**Comment by emlautarom1** [comment]
I prefer the tag one. Manually formatting strings is error prone (ex. why use `%w` here?)
