### ISSUE TITLE
Improve parameter validation in aggregator routes

### ISSUE THREAD

**Issue by Hyodar** [NethermindEth/near-sffl#239]
Basically in all API routes (REST and RPC) we are not validating parameters enough. For example, doing a non-nil check on the signed message signature or adding bounds to the checkpoint messages fetching.

**Comment by emlautarom1** [comment]
> doing a non-nil check on the signed message signature

Could you elaborate on this?

**Comment by emlautarom1** [comment]
> adding bounds to the checkpoint messages fetching

Added on #250

**Comment by Hyodar** [comment]
> Could you elaborate on this?
The signed messages `.Signature` is a pointer, even though the signed message struct itself is a value.
